### ISSUE TITLE
Use issues for TODO list?

### ISSUE THREAD

**Issue by jlumpe** [r-bioinformatics/collaboration#8]
Wondering if it may make more sense to use GitHub's issues feature instead of the `TODO.md` file. It might be a bit easier to edit and wouldn't clutter the commit history (I'm assuming it will likely be changing rapidly as we're figuring out the goal of the project).

**Comment by apfejes** [comment]
Absolutely - that was the plan.  Eventually, we'll probably break into several different project groups, and then use the issue tracker for them.

On the other hand, the repo is less than 24 hours old.... I figured the most important thing was just to get something down, and we'll clean it up later.

**Comment by jlumpe** [comment]
Sounds good!
